services:
  #  UI for Kafka and Schema-Registry, http://localhost:8090
  akhq:
    image: tchiotludo/akhq:0.24.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "redpanda:29092"
              schema-registry:
                url: "http://schema-registry:8085"
    ports:
      - "8090:8080"
    links:
      - redpanda
      - schema-registry

  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: redpandadata/redpanda:v22.3.18
    container_name: redpanda-1
    ports:
      - 9092:9092
      - 29092:29092

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    depends_on:
      - redpanda
    ports:
      - "8085:8085"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://redpanda:29092'
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8085'
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'INFO'